# Generated by Django 4.2.7 on 2023-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=12, unique=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_conductor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('folio_informe', models.IntegerField(primary_key=True, serialize=False)),
                ('factura', models.IntegerField()),
                ('tipo_devolucion', models.CharField(max_length=255)),
                ('categoria_devolucion', models.CharField(max_length=255)),
                ('motivo_devolucion', models.CharField(max_length=255, null=True)),
                ('nombre_vendedor', models.CharField(max_length=255, null=True)),
                ('transporte', models.CharField(max_length=255, null=True)),
                ('usuario_anulacion', models.CharField(max_length=255, null=True)),
                ('dev_envase_ic', models.CharField(max_length=255, null=True)),
                ('cliente_recepciona', models.CharField(max_length=255, null=True)),
                ('observacion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('factura', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('rut_cliente', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('folio_informe', models.AutoField(primary_key=True, serialize=False)),
                ('factura', models.IntegerField()),
                ('nc_requerido', models.CharField(max_length=255)),
                ('n_nc', models.IntegerField(null=True)),
                ('orden_retiro', models.CharField(max_length=255)),
                ('hoja_ruta', models.IntegerField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_informe', models.DateField()),
                ('firma_calidad', models.TextField()),
                ('firma_seleccion', models.TextField(null=True)),
                ('firma_despacho', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=50, null=True)),
                ('producto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_transporte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('tipo_permiso', models.CharField(max_length=100)),
                ('firma', models.TextField()),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosPermitidoAnular',
            fields=[
                ('id_usuario_anula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario_anula', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vendedor', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosDev',
            fields=[
                ('factura', models.IntegerField()),
                ('folio_informe', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('lote', models.IntegerField(null=True)),
                ('nombre_producto', models.CharField(max_length=255, null=True)),
                ('total_facturado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_devuelto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bodega_destino', models.CharField(max_length=255, null=True)),
                ('estado_producto', models.CharField(max_length=255, null=True)),
                ('proceso', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('factura', 'folio_informe')},
            },
        ),
        migrations.CreateModel(
            name='FacturasInformes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturas_factura', models.IntegerField()),
                ('informes_factura', models.IntegerField()),
            ],
            options={
                'unique_together': {('facturas_factura', 'informes_factura')},
            },
        ),
    ]
